name: Compile and test

on: [pull_request]

jobs:
  macos:
    name: macos | compile and test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test

  linux:
    name: linux | compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile project
      run: swift build
